### ISSUE TITLE
Starter marketing site

### ISSUE THREAD

**Issue by ZachBeta** [SpaceBarLabs/SpaceBarLabs.com#1]
First concept:  just "Space Bar Labs", a brief description, and an email address to reach us

It can just be Times New Roman  The important part is that we can be found and reached.

**Comment by benjaminoakes** [comment]
Deployed to https://spacebarlabs.com/

![Screenshot from 2024-08-23 13-21-47](https://github.com/user-attachments/assets/ef13737a-425c-43dc-8ca5-a56708f91cf5)
